version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.ornaq.in/api
        VITE_SOCKET_URL: https://api.ornaq.in/
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-439706206780-ijguhjttgfboes0b78k3cpr3snvooc7p.apps.googleusercontent.com}
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=https://api.ornaq.in/api
      - VITE_SOCKET_URL=https://api.ornaq.in/
    depends_on:
      - backend
    restart: unless-stopped
